### ISSUE TITLE
ahmetalnaddaf ödev

### ISSUE THREAD

**Issue by ahmetalnaddaf** [themanoftalent/TurkceAlgoritma#19]
1-başla
2-telefon aç ve google maps uygulamasına git
3-hedef konuma gir ve arama düğmesine bas
4-hangi araca kullanıcağını karar ver(yürüme-araba-toplu taşıma)
5-yol tarifine basıp en uygun yolu seç
6-sesli yönlendirici aç
7-hedef konuma ulaşmak
8-bitir

**Comment by themanoftalent** [comment]
Please pull request

**Comment by themanoftalent** [comment]
Pull request yapalım lütfen
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
