### ISSUE TITLE
sandviç algorıtması

### ISSUE THREAD

**Issue by Dostonbekleader** [themanoftalent/TurkceAlgoritma#35]
Doatonbek Ismonov 2111502234
1.	Başla 
2.	Lazım olan malzemeleri al;
3.	Melzemeler, piçak,  sanviç ekmeği, domates, kaşar, salam, marul;
4.	Pıçakla  Sanviç ekmeğini rasını kes,  
5.	Sanviç ekmeğini içini aç 
6.	Sanviç ekmeği içiğe domates koy
7.	Domates üstüne kaşar koy. 
8.	Kaşar ustuye salam koy 
9.	Salam ustuye marul koy
10.	Sandviç kemeklerini brleştir 
11.	Bitir.

**Comment by themanoftalent** [comment]
pull request

**Comment by themanoftalent** [comment]
(https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)
